"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=knf@n!7^q_e$nf0p+pt=kc^l_$h5iw-fidcy@$z25n3xz^ytp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'MTV.apps.MtvConfig',
    'common.apps.CommonConfig',
    'storages',
    'cacheops',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_db',
        'USER': 'django',
        'PASSWORD': 'django',
        'HOST': 'db-1.cspzvo0ks7cl.ap-northeast-2.rds.amazonaws.com',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


import os
MEDIA_URL = '/blog_sound/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'blog_sound')




# S3 Configuration

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'AKIAUHOLGTC7TUSVQZSQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'pigmamusic'
AWS_REGION="ap-northeast-2"
AWS_S3_CUSTOM_DOMAIN ="%s.s3.%s.amazonaws.com" % (AWS_STORAGE_BUCKET_NAME, AWS_REGION)
AWS_DEFAULT_ACL='public-read'
STATIC_URL = 'https://%s/static/' % (AWS_S3_CUSTOM_DOMAIN)



SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKCIE_AGE= 21600
CACHEOPS_LRU = True
CACHEOPS_DEGRADE_ON_FAILURE = True
CACHEOPS_DEFAULTS = {
                     'timeout': 60*5,
                     'cache_on_save': True,
                     'ops' : 'all'
                     }


REDIS_HOST = "redis-cluster.l0azzo.ng.0001.apn2.cache.amazonaws.com"
CACHEOPS_REDIS = {
        'host' : REDIS_HOST,
        'port' : 6379,
        'db' : 1,
        'socket_timeout': 1

 }
CACHEOPS = {
            'MTV.*' : {},
            'common.*': {},

            }

SESSION_ENGINE= 'redis_sessions.session'
SESSION_EXPIRE_SECONDS = 120
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT='/'
SESSION_REDIS={
       'host': REDIS_HOST,
       'port': 6379,
       'db':2,
       'prefix':'session',
       'socket_timeot':1,
       'retry_on_timeout': False,
       }
       
CSRF_TRUSTED_ORIGINS = ['https://www.pigmamusic.com','https://127.0.0.1:8000']

