# Generated by Django 4.1.2 on 2022-10-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image_upload',
            field=models.ImageField(blank=True, upload_to='User/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='board',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='User/data/%Y/%m/%d/'),
        ),
    ]
