# Generated by Django 4.1.2 on 2022-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0004_board_image_upload_alter_board_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='User/images/%Y/%m/%d/'),
        ),
    ]
