# Generated by Django 4.1.2 on 2022-11-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0006_remove_board_file_upload_remove_board_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(),
        ),
    ]
